name: flutter_embedding
description: This project helps embedding into a native ios or android app.
version: 0.0.1-beta.3

homepage: https://github.com/krispypen/flutter_embedding
repository: https://github.com/krispypen/flutter_embedding/tree/main/packages/flutter_embedding
issue_tracker: https://github.com/krispypen/flutter_embedding/labels/flutter_embedding

topics:
  - embedding
  - embedding-flutter
  - embedding-ios
  - embedding-android
  - embedding-react-native

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: be.krispypen.plugins.flutter_embedding
        pluginClass: FlutterEmbeddingPlugin
      ios:
        pluginClass: FlutterEmbeddingPlugin

