# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

require_relative 'Flutter/podhelper'

target 'FlutterEmbeddingExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  install_all_flutter_pods()
  # Pods for FlutterEmbeddingExample

  target 'FlutterEmbeddingExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterEmbeddingExampleUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
